/**
 * ENV VARIABLES ARE SERVER SIDE ONLY UNLESS PREFIXED WITH NEXT_PUBLIC
 */
const config = {
  JWT_SECRET: process.env.JWT_SECRET!,
  MONGODB_URI: process.env.MONGODB_URI!,

  // THESE ARE PUBLICALLY ACCESSIBLE!
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL!,
  NEXT_PUBLIC_BASE_PATH: process.env.NEXT_PUBLIC_BASE_PATH!,
  NEXT_PUBLIC_SITE_NAME: process.env.NEXT_PUBLIC_SITE_NAME!,
};

export default config;
